# For Rpi
[RaspberryPi]
klipper_section: mcu rpi
action_command: make flash

[cartographer]
klipper_section: mcu scanner
is_klipper_fw: false
action_command: ~/cartographer-klipper/scripts/firmware.py -d <canbus_uuid> -f CAN

[octopus]
klipper_section: mcu
action_command: make flash FLASH_DEVICE=/dev/serial/by-id/usb-Klipper_stm32f446xx_31003E001550335331383520-if00

[ebb36]
klipper_section: mcu ebb36
ction_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u d9a0d811b378
#action_command: python3 ~/katapult/scripts/flashtool.py -i can0 -u d9a0d811b378  
